# Generated by Django 4.2.16 on 2024-09-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(default="TBD", max_length=20),
        ),
    ]
